name: Export translations
on:
  schedule:
    - cron: "0 6,18 * * *" # Run daily at 6AM and 6PM UTC
  workflow_dispatch:
jobs:
  copy:
    name: Export translations
    runs-on: ubuntu-latest
    steps:
      - name: Clone l10n repository
        uses: actions/checkout@v3
        with:
          path: l10n_repo
      - name: Clone main code repository
        uses: actions/checkout@v3
        with:
          repository: mozilla/blurts-server
          fetch-depth: 0
          path: code_repo
          token: ${{ secrets.MONITOR_L10N_TOKEN }}
      - name: Copy translation files
        run: |
          # Use rsync to sync the content of the "locales" folder
          # Exclude hidden files, the "en" folder, markdown files
          rsync -av --progress --exclude="en/*" --exclude="*.md" --exclude=".*" l10n_repo/ code_repo/locales/
      - name: Get the current date for PR title
        run: echo "current_date=$(date +"%Y-%m-%d %H:%M")" >> $GITHUB_ENV
      - name: Commit changes and push
        run: |
          # Only try to commit if there are pending changes
          cd code_repo
          if [[ $(git diff --exit-code) || $(git ls-files --other --exclude-standard) ]]
          then
            git config user.name "mozilla-pontoon"
            git config user.email "mozilla-pontoon@users.noreply.github.com"

            # Only add files from the locales folder
            git add locales
            git commit -m "Update translations (${{ env.current_date }})"
            git push -f origin
          else
            echo "No changes found."
          fi
