name: Import source strings
on:
  schedule:
    - cron: "0 7 * * 1-5" # Run Mon-Fri at 7AM UTC
  workflow_dispatch:
jobs:
  copy:
    name: Copy strings
    runs-on: ubuntu-latest
    steps:
      - name: Clone l10n repository
        uses: actions/checkout@v3
        with:
          path: l10n_repo
      - name: Clone main code repository
        uses: actions/checkout@v3
        with:
          repository: mozilla/blurts-server
          fetch-depth: 0
          path: code_repo
      - name: Copy source files
        run: |
          cp code_repo/locales/en/*.ftl l10n_repo/en/
      - name: Get the current date for PR title
        run: echo "current_date=$(date +"%Y-%m-%d")" >> $GITHUB_ENV
      - uses: peter-evans/create-pull-request@v4
        with:
          path: l10n_repo
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          commit-message: Extract new source strings
          branch: l10n_automation
          delete-branch: true
          title: "Extract new strings (${{ env.current_date }})"
